{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ingress-gateway.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ingress-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.Service }} # Itera sobre as configurações de serviços no arquivo values.yaml
    {{- range .routes }} # Itera sobre as rotas definidas para o serviço
    {{- range .hosts }} # Itera sobre os hosts associados a cada rota
    - host: {{ .host }} # Define o host para o qual esta regra se aplica
      http:
        paths:
        {{- range .paths }} # Itera sobre as paths dentro deste host
          - path: {{ .path }} # Define o o path para esta regra
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .serviceName }}
                port:
                  number: 80
              {{- else }}
              serviceName: {{ .serviceName }} #realese/namespace?
              servicePort: 80 #declação
              {{- end }}
        {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}